import bpy

def rename_bones():
    
    dict = {
        # Torso
        'RibHelper.L': 'LRibHelper',
        'RibHelper.R': 'RRibHelper',
        'Breast_skin.L': 'LBreast_skin',
        'Breast_skin.R': 'RBreast_skin',
        # Left Leg
        'ButtFat_skin.L': 'LButtFat_skin',
        'Leg_Thigh_skin.L': 'LLeg_Thigh_skin',
        'Leg_Thigh.L': 'LLeg_Thigh',
        'Leg_Thigh_Low_skin.L': 'LLeg_Thigh_Low_skin',
        'Leg_Thigh_Fat_skin.L': 'LLeg_Thigh_Fat_skin',
        'Leg_Calf.L': 'LLeg_Calf',
        'Leg_Calf_skin.L': 'LLeg_Calf_skin',
        'Leg_Calf_Low_skin.L': 'LLeg_Calf_Low_skin',
        'Leg_Foot.L': 'LLeg_Foot',
        'Leg_Toe1.L': 'LLeg_Toe1',
        # Left Arm
        'Arm_ForeArm3_skin.L': 'LArm_ForeArm3_skin',
        'Arm_ForeArm2_skin.L': 'LArm_ForeArm2_skin',
        'Arm_ForeArm1_skin.L': 'LArm_ForeArm1_skin',
        'Arm_ForeArm3.L': 'LArm_ForeArm3',
        'Arm_ForeArm2.L': 'LArm_ForeArm2',
        'Arm_ForeArm1.L': 'LArm_ForeArm1',
        'Arm_UpperTwist1_skin.L': 'LArm_UpperTwist1_skin',
        'Arm_UpperTwist2_skin.L': 'LArm_UpperTwist2_skin',
        'Arm_UpperTwist1.L': 'LArm_UpperTwist1',
        'Arm_UpperTwist2.L': 'LArm_UpperTwist2',
        'Arm_UpperFat_skin.L': 'LArm_UpperFat_skin',
        'Arm_UppeLArm.L': 'LArm_UppeLArm',
        'Arm_UppeLArm_skin.L': 'LArm_UppeLArm_skin',
        'Arm_ShoulderFat_skin.L': 'LArm_ShoulderFat_skin',
        'Arm_Collarbone.L': 'LArm_Collarbone',
        'Arm_Collarbone_skin.L': 'LArm_Collarbone_skin',
        'Arm_UpperTwist2_skin.L': 'LArm_UpperTwist2_skin',
        'Arm_ForeArm1_skin.L': 'LArm_ForeArm1_skin',
        'Arm_ForeArm3_skin.L': 'LArm_ForeArm3_skin',
        'Arm_Hand.L': 'LArm_Hand',
        # Left Fingers
        'Arm_Finger11.L': 'LArm_Finger11',
        'Arm_Finger12.L': 'LArm_Finger12',
        'Arm_Finger13.L': 'LArm_Finger13',
        'Arm_Finger21.L': 'LArm_Finger21',
        'Arm_Finger22.L': 'LArm_Finger22',
        'Arm_Finger23.L': 'LArm_Finger23',
        'Arm_Finger31.L': 'LArm_Finger31',
        'Arm_Finger32.L': 'LArm_Finger32',
        'Arm_Finger33.L': 'LArm_Finger33',
        'Arm_Finger41.L': 'LArm_Finger41',
        'Arm_Finger42.L': 'LArm_Finger42',
        'Arm_Finger43.L': 'LArm_Finger43',
        'Arm_Finger51.L': 'LArm_Finger51',
        'Arm_Finger52.L': 'LArm_Finger52',
        'Arm_Finger53.L': 'LArm_Finger53',
        # Right Leg
        'ButtFat_skin.R': 'RButtFat_skin',
        'Leg_Thigh_skin.R': 'RLeg_Thigh_skin',
        'Leg_Thigh.R': 'RLeg_Thigh',
        'Leg_Thigh_Low_skin.R': 'RLeg_Thigh_Low_skin',
        'Leg_Thigh_Fat_skin.R': 'RLeg_Thigh_Fat_skin',
        'Leg_Calf.R': 'RLeg_Calf',
        'Leg_Calf_skin.R': 'RLeg_Calf_skin',
        'Leg_Calf_Low_skin.R': 'RLeg_Calf_Low_skin',
        'Leg_Foot.R': 'RLeg_Foot',
        'Leg_Toe1.R': 'RLeg_Toe1',
        # Right Arm
        'Arm_ForeArm3_skin.R': 'RArm_ForeArm3_skin',
        'Arm_ForeArm2_skin.R': 'RArm_ForeArm2_skin',
        'Arm_ForeArm1_skin.R': 'RArm_ForeArm1_skin',
        'Arm_ForeArm3.R': 'RArm_ForeArm3',
        'Arm_ForeArm2.R': 'RArm_ForeArm2',
        'Arm_ForeArm1.R': 'RArm_ForeArm1',
        'Arm_UpperTwist1_skin.R': 'RArm_UpperTwist1_skin',
        'Arm_UpperTwist2_skin.R': 'RArm_UpperTwist2_skin',
        'Arm_UpperTwist1.R': 'RArm_UpperTwist1',
        'Arm_UpperTwist2.R': 'RArm_UpperTwist2',
        'Arm_UpperFat_skin.R': 'RArm_UpperFat_skin',
        'Arm_UpperArm.R': 'RArm_UpperArm',
        'Arm_UpperArm_skin.R': 'RArm_UpperArm_skin',
        'Arm_ShoulderFat_skin.R': 'RArm_ShoulderFat_skin',
        'Arm_Collarbone.R': 'RArm_Collarbone',
        'Arm_Collarbone_skin.R': 'RArm_Collarbone_skin',
        'Arm_UpperTwist2_skin.R': 'RArm_UpperTwist2_skin',
        'Arm_ForeArm1_skin.R': 'RArm_ForeArm1_skin',
        'Arm_ForeArm3_skin.R': 'RArm_ForeArm3_skin',
        'Arm_Hand.R': 'RArm_Hand',
        # Right Fingers
        'Arm_Finger11.R': 'RArm_Finger11',
        'Arm_Finger12.R': 'RArm_Finger12',
        'Arm_Finger13.R': 'RArm_Finger13',
        'Arm_Finger21.R': 'RArm_Finger21',
        'Arm_Finger22.R': 'RArm_Finger22',
        'Arm_Finger23.R': 'RArm_Finger23',
        'Arm_Finger31.R': 'RArm_Finger31',
        'Arm_Finger32.R': 'RArm_Finger32',
        'Arm_Finger33.R': 'RArm_Finger33',
        'Arm_Finger41.R': 'RArm_Finger41',
        'Arm_Finger42.R': 'RArm_Finger42',
        'Arm_Finger43.R': 'RArm_Finger43',
        'Arm_Finger51.R': 'RArm_Finger51',
        'Arm_Finger52.R': 'RArm_Finger52',
        'Arm_Finger53.R': 'RArm_Finger53',
    }
    
    for b in bpy.context.object.data.bones:
        if b.name in dict.keys():
            b.name = dict[b.name]

rename_bones()
